/**
	Generated by sails-inverse-model
	Date:Mon Dec 19 2022 22:51:03 GMT-0800 (Pacific Standard Time)
*/

module.exports = {
  attributes: {
    ville: {
      type: 'string',
      required: true
    },
    lot: {
      type: 'string',
    },
    code: {
      type: 'string',
      required: true,
      example: 1
    }
  }
};
