/**
	Generated by sails-inverse-model
	Date:Thu Dec 08 2022 16:52:47 GMT+0300 (heure normale d’Afrique de l’Est)
*/

module.exports = {
  attributes: {
    reference: {
      type: 'string',
      required: true
    },
    // article: {
    //     model: 'Produit',
    //     required: true
    // },
    TypeMouvement: {
      type: 'boolean',
      required: false
    },
    Quantite: {
      type: 'number',
      required: true
    },
    Date: {
      type: 'ref',
      columnType:'datetime',
      required: true
    },
    Responsable: {
      model: 'Responsable',
      required: true
    },
    Destination: {
      model: 'Localisation',
      required: true
    },

    produit: {
      model: 'Produit',
      required: true
    },

  }
};
