/**
	Generated by sails-inverse-model
	Date:Sat Dec 17 2022 17:18:10 GMT+0300 (heure normale d’Afrique de l’Est)
*/

module.exports = {
  attributes: {
    nomArticle: {
      type: 'string',
      required: true
    },
    reference: {
      type: 'string',
      required: true
    },
    designation: {
      type: 'string',
    },
    movement : {
      collection: 'Mouvement',
      via: 'produit'
    }

  }
};
